package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.CursedRoom.java
//  @ Date : 2024. 03. 20.
//  @ Author : 
//
//




/** */
public class CursedRoom extends Room {
	/** */
	public void () {
	}
}
