package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.Defendable.java
//  @ Date : 2024. 03. 20.
//  @ Author :
//
//




/** */
public interface Defendable {
    /** */
    public boolean CanDefend();

}
