package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.DoorSide.java
//  @ Date : 2024. 03. 20.
//  @ Author : 
//
//




/** */
public class DoorSide {
	/** */
	private boolean canBeOpened;
	
	/** */
	private boolean isVisible;
	
	/** */
	private Room door;
	
	/** */
	private Room doors;
	
	/** */
	private Room room;
	
	/** */
	private DoorSide pair;
	
	/** */
	public void CloneAttributes(DoorSide d) {
	}
	
	/** */
	public void ConnectDoors(DoorSide d) {
	}
	
	/** */
	public DoorSide GetPair() {
	}
	
	/** */
	public DoorSide SetPair() {
	}
	
	/** */
	public Room GetRoom() {
	}
	
	/** */
	public void SetRoom(Room r) {
	}
	
	/** */
	public void SetCanBeOpened(boolean b) {
	}
	
	/** */
	public void SetIsVisible(boolean b) {
	}
	
	/** */
	public boolean GetCanBeOpened() {
	}
	
	/** */
	public boolean GetIsVisible() {
	}
}
