package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.Game.java
//  @ Date : 2024. 03. 20.
//  @ Author : 
//
//




/** */
public class Game {
	/** */
	private int gameTimer;
	
	/** */
	private bool isEndGame;
	
	/** */
	private Person turnOrder;
	
	/** */
	private Person currentTurn;
	
	/** */
	private Person currentTurn;
	
	/** */
	private Room rooms;
	
	/** */
	public void StartGame() {
	}
	
	/** */
	public void EndGame(bool winSide) {
	}
	
	/** */
	public void NextTurn() {
	}
	
	/** */
	public bool AnyStudentsAlive() {
	}
	
	/** */
	public void RemoveFromGame(Person p) {
	}
	
	/** */
	public void AddRoom(Room r) {
	}
	
	/** */
	public void RemoveRoom(Room r) {
	}
}
