package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.HolyBeerCup.java
//  @ Date : 2024. 03. 20.
//  @ Author : 
//
//




/** */
public class HolyBeerCup extends Item implements Usable {
	/** */
	private int effectDuration;
	
	/** */
	private bool isActivated;
	
	/** */
	public bool Activate() {
	}
	
	/** */
	public void Decrement() {
	}
	
	/** */
	public bool PickedUpStudent(Student st) {
	}
	
	/** */
	public bool PickedUpInstructor(Instructor i) {
	}
	
	/** */
	public void Thrown(Person p) {
	}
	
	/** */
	public void UsedByStudent(Student s) {
	}
	
	/** */
	public void UsedByInstructor(Instructor i) {
	}
	
	/** */
	public bool PickedUpStudent(Student st) {
	}
	
	/** */
	public bool PickedUpInstructor(Instructor i) {
	}
	
	/** */
	public void Thrown(Person p) {
	}
}
