package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.Instructor.java
//  @ Date : 2024. 03. 20.
//  @ Author : 
//
//




/** */
public class Instructor extends Person {
	/** */
	private int stunDuration;
	
	/** */
	private Room room;
	
	/** */
	public void AppearInRoom(Room r) {
	}
	
	/** */
	public void StealSoul(Student st) {
	}
	
	/** */
	public void Stun(int duration) {
	}
	
	/** */
	public void DecrementStun() {
	}
	
	/** */
	public void StartTurn() {
	}
	
	/** */
	public void EndTurn() {
	}
	
	/** */
	public void UseItem(Usable u) {
	}
	
	/** */
	@Override
	public boolean Pickup(Item i) {
		return false;
	}
	
	/** */
	public void SetRoom(Room r) {
	}

	

	

}
