package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.Person.java
//  @ Date : 2024. 03. 20.
//  @ Author : 
//
//


import java.util.List;

/** */
public abstract class Person {
	/** */
	private boolean isFainted;
	
	/** */
	private boolean activeTurn;
	
	/** */
	private boolean hasWetTableCloth;
	
	/** */
	private boolean hasTVSZ;
	
	/** */
	private boolean hasFFP2Mask;
	
	/** */
	public boolean hasHolyBeerCup;
	
	/** */
	private Item inventory;

	
	/** */
	private Room room;
	
	/** */
	private WetTableCloth wetTableClothes;
	
	/** */
	private TVSZ tvszs;
	
	/** */
	private HolyBeerCup holyBeerCups;
	
	/** */
	private FFP2Mask ffp2Masks;
	
	/** */
	public void SetIsFainted(boolean b) {
	}
	
	/** */
	public void DecrementFaint() {
	}
	
	/** */
	public abstract void AppearInRoom(Room r);
	
	/** */
	public void Move(DoorSide d) {
	}
	
	/** */
	public abstract boolean Pickup(Item i);
	
	/** */
	public void Throw(Item i) {
	}
	
	/** */
	public void ThrowAllItems() {
	}
	
	/** */
	public abstract void UseItem(Usable u);
	
	/** */
	public abstract void StartTurn();
	
	/** */
	public abstract void EndTurn();
	
	/** */
	public void AddToInventory(Item i) {
	}
	
	/** */
	public void RemoveFromInventory(Item i) {
	}
	
	/** */
	public boolean DefendFromKill() {
		return false;
	}
	
	/** */
	public boolean DefendFromGas() {
		return false;
	}
	
	/** */
	public void AddWetTableCloth(WetTableCloth w) {
	}
	
	/** */
	public void AddTVSZ(TVSZ t) {
	}
	
	/** */
	public void AddFFP2Mask(FFP2Mask f) {
	}
	
	/** */
	public void AddHolyBeerCup(HolyBeerCup h) {
	}
	
	/** */
	public void RemoveWetTableCloth(WetTableCloth w) {
	}
	
	/** */
	public void RemoveTVSZ(TVSZ t) {
	}
	
	/** */
	public void RemoveFFP2Mask(FFP2Mask f) {
	}
	
	/** */
	public void RemoveHolyBeerCup(HolyBeerCup h) {
	}
	
	/** */
	public Item GetRandomActive(List<Item> list) {
		return null;
	}
}
