package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.Person.java
//  @ Date : 2024. 03. 20.
//  @ Author : 
//
//




/** */
public abstract class Person {
	/** */
	private bool isFainted;
	
	/** */
	private bool activeTurn;
	
	/** */
	private bool hasWetTableCloth;
	
	/** */
	private bool hasTVSZ;
	
	/** */
	private bool hasFFP2Mask;
	
	/** */
	public bool hasHolyBeerCup;
	
	/** */
	private Item inventory;
	
	/** */
	private Item inventory;
	
	/** */
	private Room room;
	
	/** */
	private WetTableCloth wetTableClothes;
	
	/** */
	private TVSZ tvszs;
	
	/** */
	private HolyBeerCup holyBeerCups;
	
	/** */
	private FFP2Mask ffp2Masks;
	
	/** */
	public void SetIsFainted(bool b) {
	}
	
	/** */
	public void DecrementFaint() {
	}
	
	/** */
	public abstract void AppearInRoom(Room r);
	
	/** */
	public void Move(DoorSide d) {
	}
	
	/** */
	public abstract bool Pickup(Item i);
	
	/** */
	public void Throw(Item i) {
	}
	
	/** */
	public void ThrowAllItems() {
	}
	
	/** */
	public abstract void UseItem(Usable u);
	
	/** */
	public abstract void StartTurn();
	
	/** */
	public abstract void EndTurn();
	
	/** */
	public void AddToInventory(Item i) {
	}
	
	/** */
	public void RemoveFromInventory(Item i) {
	}
	
	/** */
	public bool DefendFromKill() {
	}
	
	/** */
	public bool DefendFromGas() {
	}
	
	/** */
	public void AddWetTableCloth(WetTableCloth w) {
	}
	
	/** */
	public void AddTVSZ(TVSZ t) {
	}
	
	/** */
	public void AddFFP2Mask(FFP2Mask f) {
	}
	
	/** */
	public void AddHolyBeerCup(HolyBeerCup h) {
	}
	
	/** */
	public void RemoveWetTableCloth(WetTableCloth w) {
	}
	
	/** */
	public void RemoveTVSZ(TVSZ t) {
	}
	
	/** */
	public void RemoveFFP2Mask(FFP2Mask f) {
	}
	
	/** */
	public void RemoveHolyBeerCup(HolyBeerCup h) {
	}
	
	/** */
	public Item GetRandomActive(Item* iList) {
	}
}
