package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.Skeleton.java
//  @ Date : 2024. 03. 20.
//  @ Author : 
//
//




/** */
public class Skeleton {
}
