package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.Student.java
//  @ Date : 2024. 03. 20.
//  @ Author : 
//
//




/** */
public class Student extends Person {
	/** */
	private boolean isAlive;
	
	/** */
	private Game game;
	
	/** */
	private Room room;
	
	/** */
	public void AppearInRoom(Room r) {
	}
	
	/** */
	public void StartTurn() {
	}
	
	/** */
	public void EndTurn() {
	}
	
	/** */
	public boolean Die() {
		return false;
	}
	
	/** */
	public void UseItem(Usable u) {
	}
	
	/** */
	public void ConnectTransistors(Transistor t1, Transistor t2) {
	}
	
	/** */
	public boolean Pickup(Item i) {
		return false;
	}
	
	/** */
	public void SetRoom(Room r) {
	}


}
