package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.Transistor.java
//  @ Date : 2024. 03. 20.
//  @ Author : 
//
//




/** */
public class Transistor extends Item implements Usable {
	/** */
	private bool isActive;
	
	/** */
	public bool Activate() {
	}
	
	/** */
	public void SetPairs(Transistor t1, Transistor t2) {
	}
	
	/** */
	public void SetPair(Transistor t) {
	}
	
	/** */
	public Transistor GetPair() {
	}
	
	/** */
	public bool PickedUpStudent(Student st) {
	}
	
	/** */
	public bool PickedUpInstructor(Instructor i) {
	}
	
	/** */
	public void Thrown(Person p) {
	}
	
	/** */
	public void UsedByStudent(Student s) {
	}
	
	/** */
	public void UsedByInstructor(Instructor i) {
	}
	
	/** */
	public bool PickedUpStudent(Student st) {
	}
	
	/** */
	public bool PickedUpInstructor(Instructor i) {
	}
	
	/** */
	public void Thrown(Person p) {
	}
}
