package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.TVSZ.java
//  @ Date : 2024. 03. 20.
//  @ Author : 
//
//




/** */
public class TVSZ extends Item {
	/** */
	private int usesLeft;
	
	/** */
	public void Decrement() {
	}
	
	/** */
	public bool PickedUpStudent(Student st) {
	}
	
	/** */
	public bool PickedUpInstructor(Instructor i) {
	}
	
	/** */
	public void Thrown(Person p) {
	}
	
	/** */
	public bool PickedUpStudent(Student st) {
	}
	
	/** */
	public bool PickedUpInstructor(Instructor i) {
	}
	
	/** */
	public void Thrown(Person p) {
	}
}
