package modul;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : modul.Usable.java
//  @ Date : 2024. 03. 20.
//  @ Author : 
//
//




/** */
public class Usable {
	/** */
	public bool Activate() {
	}
	
	/** */
	public void UsedByStudent(Student s) {
	}
	
	/** */
	public void UsedByInstructor(Instructor i) {
	}
}
