name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 22.0.1+8
      uses: actions/setup-java@v2
      with:
        java-version: '22.0.1+8'
        distribution: 'adopt'

    - name: Compile and run the Java code
      id: run_tests
      run: |
        cd Logarlec
        mkdir -p build/classes/test
        javac -cp "lib/json-20240303.jar:src" -d build/classes/test src/test/Tester.java src/test/TestRunAllMain.java
        output=$(java -cp "build/classes/test:lib/json-20240303.jar" test.TestRunAllMain)
        echo "$output"
        echo "::set-output name=full_output::$output"
      
    - name: Check for FAIL in the output
      run: |
        full_output="${{ steps.run_tests.outputs.full_output }}"
        if echo "$full_output" | grep -q 'FAIL'; then
          echo "The output contains FAIL"
          exit 1
        else
          echo "The output does not contain FAIL"
        fi
  
