name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 22.0.1+8
      uses: actions/setup-java@v2
      with:
        java-version: '22.0.1+8'
        distribution: 'adopt'

    - name: Compile and run the Java code
      run: |
        cd Logarlec
        mkdir -p build/classes/test
        javac -cp "lib/json-20240303.jar:src" -d build/classes/test src/util/Reader.java src/test/Tester.java src/test/PrototypeMain.java
        java -cp "build/classes/test:lib/json-20240303.jar" test.PrototypeMain 
        run all || (grep -q 'FAILED' <<< "$OUTPUT" && exit 1)
      env:
        OUTPUT: ${{ steps.build.outputs.output }}
